# Generated by Django 5.1.1 on 2024-10-11 10:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsidiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('phone_no', models.IntegerField()),
                ('emp_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelancer', 'Freelancer')], max_length=20)),
                ('profile_image', models.ImageField(default='static/profile_images/default.png', null=True, upload_to='employees/profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiaries.subsidiaries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
